### ISSUE TITLE
Race condition of queryset in read_frame

### ISSUE THREAD

**Issue by jacksund** [chrisdev/django-pandas#138] opened 2021-09-15 15:53 UTC
I'm seeing a change in set size between the original queryset and the read_frame dataframe. This occurs when entries are inserted into the database between (i) when the original queryset is made and (ii) when the dataframe is created.

Here's an example of when this occurs:

```python
# First we set up the query but it is not made yet 
from somepackage import MyModel
queryset = MyModel.objects.all()

# Next we convert to the pandas dataframe
from django_pandas.io import read_frame
dataframe = read_frame(queryset)

# Here is where some new object(s) is inserted into the database.
# Note this could occur is a completely separate process from 
# the one running here. This sets up the race condition.

# If we wanted to add a column to the dataframe using a method
# attached to the original queryset, this is how we'd do it
dataframe["my_column"] = [x.get_some_value() for x in queryset]
# This will raise an error though as the length of this new list will
# no longer equal the rows in dataframe.
```

It looks like the `read_frame` method initiates a new query, so there's no guarantee that `len(queryset) == len(dataframe)`.

**Comment by phkrhateaid** [comment] 2021-09-16 11:21
This is expected behaviour because django does a lazy evaluation of querysets.

**Comment by chrisdev** [comment] 2021-11-05 18:42
@jacksund we could not reproduce this behaviour. Have you looked at the tests suite?  I should be pretty easy to add a test that replicates the behaviour you tried described above. So I'm closing this for now. When you submit a test that replicates the behaviour described above we reopen this issue.

**Closed by chrisdev** 2021-11-05 18:42 UTC

**Comment by jacksund** [comment] 2021-11-05 18:57
Thanks for the reply. I've side-stepped this issue in my code, so I probably won't submit a test any time soon... I'll revisit this once my package becomes stable though. Until then, cheers :smile:

**Comment by chrisdev** [comment] 2021-11-05 19:10
@jacksund. Thanks for your submission. We're sorry for taking so long to respond to your issue as we were caught up in other projects and then I got an M1 Air and have been struggling to get my development environment back up and running. Once again thanks for submitting the issue and we look forward to you revisiting it when you get a chance
